### ISSUE TITLE
[question] Modification to use vertical  display 

### ISSUE THREAD

**Issue by radsonpatrick** [englmaxi/zmk-dongle-display#2]
I am using a 128x32 OLED display, and I would like to rotate the icons displayed to improve the layout and arrangement on the screen. Currently, the icons are not optimally oriented for this display size and orientation.
![image](https://github.com/user-attachments/assets/6a337919-ece3-4750-8b02-b776240a65c0)

**Comment by radsonpatrick** [comment]
my intencion is rotaete and realocate objects ! 
example rotate icon bluetooth im try add this functions `lv_img_set_angle(bt,900);`  or ` lv_obj_set_style_transform_angle(bt, 900, 0);` in `./boards/shields/dongle_display/widgets/output_status.c` 

but after compile  the icon is blank !

you help-me ?

**Comment by englmaxi** [comment]
It seems that there is no easy way to rotate the entire screen: https://github.com/zmkfirmware/zmk/issues/1749

You can use the mentioned workaround or, instead of rotating the images via LVGL, try to rotate the original images.

<details>
  <summary>original image files</summary>

![sym_1](https://github.com/user-attachments/assets/046ebf57-9706-47f0-8295-7c55828fc3c2)
![sym_2](https://github.com/user-attachments/assets/4cee393c-58e2-47f1-830c-4bffb676772b)
![sym_3](https://github.com/user-attachments/assets/986b7137-916d-448d-98bc-2b3e2e9a8450)
![sym_4](https://github.com/user-attachments/assets/aa690a60-8469-4abe-978a-af3bc1e55554)
![sym_5](https://github.com/user-attachments/assets/36bca001-899f-410c-99cb-e76662a2d1a6)
![sym_bt](https://github.com/user-attachments/assets/5e28f6c5-1d68-4bc9-8bb9-f7190b371932)
![sym_nok](https://github.com/user-attachments/assets/37d544db-d0a8-4805-a0b0-3e10402561c6)
![sym_ok](https://github.com/user-attachments/assets/3bd740eb-a5cd-44a0-a78a-a0547f527f2f)
![sym_open](https://github.com/user-attachments/assets/14f79595-e615-4e2e-ae97-7dc5cd2e35d3)
![sym_usb](https://github.com/user-attachments/assets/bd6b820a-7919-4820-89b4-2a7e1377215d)
![control](https://github.com/user-attachments/assets/1b94657e-9490-40c7-b044-29a1f00a29be)
![shift](https://github.com/user-attachments/assets/cd5c0b88-fe5c-4a5d-a37b-ea9519bb20ee)
![windows](https://github.com/user-attachments/assets/5b4eacdc-f5e4-4504-abd8-54ad0acd69b8)
![alt](https://github.com/user-attachments/assets/cac0f1a4-9dff-4e45-b1cf-0d61f02222a2)
![both1_open](https://github.com/user-attachments/assets/942edc46-0145-4a8b-94db-5a2c739008eb)
![both2](https://github.com/user-attachments/assets/568c70cc-8bd7-487e-926e-7e504fe4f9cb)
![left1](https://github.com/user-attachments/assets/cc975aae-2eec-4f4c-8820-0d9a1953daea)
![left2](https://github.com/user-attachments/assets/f28dcc35-3bb7-4a31-be56-0f837faf2c78)
![none](https://github.com/user-attachments/assets/0563e7b7-a324-46df-a46f-9853a3c20ad0)
![right1](https://github.com/user-attachments/assets/06ce5ffe-1a3e-423c-afda-66d47116bf2e)
![right2](https://github.com/user-attachments/assets/6cb19167-f830-4f78-9274-ea1539014202)
![both1](https://github.com/user-attachments/assets/fd31989f-6efb-4b60-bff1-00035314616b)

</details>
